### ISSUE TITLE
Controls reset when switching version.

### ISSUE THREAD

**Issue by Xrey274** [EnnuiL/OkZoomer#18]
Switching to a  Vanilla version of the game and  reverting back to Fabric (with OkZoomer) resets custom keybinds.

**Comment by Jefaxe** [comment]
Yeah, thats how controls work sadly :(. Minecraft uses options.txt, which isn't any config format, so unknown options are deleted when reading and rewriting the. Fabric just adds keybinds to the list of stuff to get added to options.txt, and minecraft does it. I really hope mojang switch to options.yml, options.json, options.toml, options.json5, options.hjson, opions.xml, options.cfg, or options.ini (i'd like JSON, but thats just my preference).

**Comment by Xrey274** [comment]
How come other mods remember their keybinds?

**Comment by RDKRACZ** [comment]
They don’t? I tested it just for you with ChestTracker, Where Is It and Map Atlases.
