### ISSUE TITLE
Make zooming possible only when certain item is in the inventory.

### ISSUE THREAD

**Issue by RDKRACZ** [EnnuiL/OkZoomer#20]
Add optional check to make zooming work only when a configurable (enter ID) item is present in the inventory.
Firstly I wanted something like a spyglass but realized I can do the item by myself.

**Comment by peppzyy** [comment]
or u can use spyglass bind mod just search it in curseforge

**Comment by Danklor** [comment]
I like RDKRACZ's suggestion. Although the Quick Spyglass mod does this I find OK Zoomer to work much better overall.

**Comment by EnnuiL** [comment]
Implemented on Ok Zoomer 5.0.0-beta.4 as the "Require Item" value of the Spyglass Dependency option, with the option itself being able of doing much more
